version: '3'
services:
  redis:
    image: redis
    container_name: s_redis
    privileged: true
    command: redis-server --requirepass Jz123456
    volumes:
      - /Users/chenweilong/redis/home/redis:/data
    ports:
      - "6379:6379"
